name: TryHackMe Badge Updater

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-tryhackme-badge:
    name: Update TryHackMe Badge Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Download the latest badge image
      - name: Fetch TryHackMe Badge Image
        run: |
          curl -o ./assets/thm_propic.png https://tryhackme-badges.s3.amazonaws.com/RobasAhmedShah.png

      # Step 3: Commit and push the updated badge image
      - name: Commit and Push Badge Update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./assets/thm_propic.png
          git commit -m "Updated TryHackMe badge image"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
